name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

#   setup:
#     runs-on: macos-10.15
#     steps:
#     - name: Set up Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.16.4

  build:
    runs-on: macos-10.15
#     needs: [setup]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: input
      run: |
        echo "::set-output name=i1::myinput1\n"
        echo "::set-output name=i2::myinput2\n"
      id: input_id

    - name: output
      run: echo ${{ steps.input_id.outputs.i1 }}

#     - name: Build Mac Intel
#       run: make build GOOS=darwin GOARCH=amd64

#     - name: Build Mac Apple Silicon
#       run: make build GOOS=darwin GOARCH=arm64

    - name: ls -ltr
      run: ls -ltr

    - name: Test
      run: ./mdr --version
