name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup:
    runs-on: macos-10.15
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.4

  build:
    runs-on: macos-10.15
    needs: [setup]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build Mac Intel
      run: make build GOOS=darwin GOARCH=amd64

#     - name: Build Mac Apple Silicon
#       run: make build GOOS=darwin GOARCH=arm64

    - name: ls -ltr
      run: ls -ltr

    - name: Test
      run: ./mdr --version
