name: Pipeline

on:

  push:
    branches: [ main ]
    tags: [ "v*" ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-release:
    name: Build and Release
    runs-on: macos-10.15
    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.4

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build Mac Intel
      run: make build GOOS=darwin GOARCH=amd64

    - name: Test Mac Intel
      run: ./mdr_v*_amd64 --version

    - name: Build Mac M1/Apple Silicon
      run: make build GOOS=darwin GOARCH=arm64

    - name: Test Mac M1/Apple Silicon
      run: ./mdr_v*_arm64 --version 2>&1 | grep -i 'bad CPU type'

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: mdr*
